### ISSUE TITLE
Add a module to validate a review

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-ipfs-support#27]
This module can be used by marketplaces to validate a discovered review. The validation is specified here - https://github.com/ChluNetwork/chlu-protocol/blob/master/chlu_protocol.md#validating-a-review

**Comment by fazo96** [comment]
List of validations that we need to perform (roughly in order):

- [ ] verify presence on the blockchain if the review was not discovered from it and the library has access, this is assuming the review is discovered along with a reference to the transaction ID
- [ ] verify internal RR hash (it is calculated after all other crypto operations)
- [ ] if the RR is encrypted, decrypt review record using vendor public key
- [ ] validate PoPR signature using pub key from vendor if the PoPR is signed
- [ ] if the review record is an update, check that information apart from the review itself matches the old version(s)
- [ ] if we have information about the blockchain transaction, check that addresses and amounts are matching

Also we should add an option to fail the validation if the signature or the encryption is missing

**Comment by kulpreet** [comment]
We need the PoPR to be signed. Maybe we need to do the key setup part first. But for the first demo, lets put in a mock PoPR validation function that returns true.

**Comment by fazo96** [comment]
Updated comment with the validations that I split out from the #37

**Comment by fazo96** [comment]
@kulpreet Closing this and moving the blockchain stuff to a new issue #85
