### ISSUE TITLE
Store hash pointer to last review by the customer when creating a new review

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-ipfs-support#32]

**Comment by fazo96** [comment]
In [the paper](https://chlu.io/papers/position-paper.pdf) at paragraph 5.9.1 it says that the hash stored in a review is of the last review created by the same user even if it is not related to the same transaction, this is needed to make the approximate timestamping work.

In the title of this issue it says to store the pointer to the last review about the same transaction. We should point to the last review even if it is unrelated to the transaction right?

**Comment by kulpreet** [comment]
Yes, you are right. Good spot. Fixed title.
