### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-ipfs-support#4]
Some data should not be lost between instances of the API:

Customer (Browser)

- OrbitDB address and local copy
- identity information (keys) for OrbitDB and IPFS
- IPFS store

Service node

- OrbitDB addresses and local copy
- IPFS store

**Comment by kulpreet** [comment]
@fazo96 this issue is closed now, right?

**Comment by fazo96** [comment]
It should automatically close when we merge #12
