### ISSUE TITLE
Start versioning packages and deploy to NPM

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-ipfs-support#61]
Libraries:

- [x] chlu-ipfs
  - [x] CHANGELOG.md
  - [x] required tooling and configuration, if any
  - [ ] release first version on NPM
- [ ] chlu-wallet
  - [ ] CHANGELOG.md
  - [ ] required tooling and configuration, if any
  - [ ] release first version on NPM
- [x] chlu-marketplace
  - [ ] CHANGELOG.md
  - [x] required tooling and configuration, if any
  - [ ] release first version on NPM

Should we do apps as well? Also maybe we should rename chlu-wallet-support to chlu-bitcoin?

**Comment by fazo96** [comment]
We decided not to publish to NPM
