### ISSUE TITLE
OrbitDB validation and Index improvements

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-ipfs-support#76]
This is what didn't make it in PR #70 

- [ ] validation: only put in the index valid stuff
  - [ ] use an OrbitDB release with support for async index update operations (https://github.com/orbitdb/orbit-db-store/issues/18)
  - [ ] make sure all the required data is pinned or at least cached while validating
  - [ ] validate RR
  - [ ] validate forward pointers
  - [ ] validate TX stuff
- [x] expose API to get RR list
- [x] figure out a way to avoid replicating invalid operations (https://github.com/orbitdb/ipfs-log/issues/117)
- [x] specific tests for the Chlu Store
- [x] sort the RRs: the RR list is sorted with latest first, in order of submission to the DB. Works fine for now
- [ ] investigate the possibility of using a lighter index for non-service nodes
- [ ] rewrite/refactor the index to make sure it can handle a large amount of data
- [ ] on service nodes after replicating, go through the new reviews and run the replication/validation code. Keep progress and validation info in the index
- [ ] emit events for discovered review records and updates
- [ ] replace the replaceable pubsub stuff with events emitted by orbit-db store/index

**Comment by fazo96** [comment]
Opened a PR to ipfs-log to handle validating Entries in Logs, so that we can avoid replicating bad data: https://github.com/orbitdb/ipfs-log/pull/123

**Comment by fazo96** [comment]
@kulpreet We need a better way to keep the index, especially on service nodes. For now we keep it in memory but that's bad as it grows, since it will use too much memory.

I searched a little and found these possible solutions:

- js-data
  - has many adapters so it can work on top of a lot of DBs
  - works with localstorage in the browser, or a REST backend
  - a little complicated configuration, and unusual API
  - popular, slow development
- dexie
  - works only in the browser with IndexedDB
  - looks really good API-wise
  - maybe works in node using an IndexedDB polyfill, but it's hacky at best so I would avoid
  - very popular, slow development
- WebSQL
  - native SQLite in the browser (it's not a library)
  - doesn't work in firefox
- SQL.js
  - SQLite implementation for the browser, using emscripten
  - Very popular. Could use this in the browser and use native SQLite in node.js, which is also what they suggest
- AlaSQL
  - weird webpack config required. This is a problem for us
  - claims to be faster than alternatives
  - weird configuration in node.js
  - looks really good and has clear performance and benchmarks. Too bad for that webpack problem
- Taffy
  - it's in memory so it solves nothing for us

**Comment by kulpreet** [comment]
Just to be sure I understand this clearly. You are saying we need to use a database in our custom store for orbitDB? I suspect we'll need to do this soon, so has the time come?

**Comment by fazo96** [comment]
Yep, not sure exactly when the in memory one will stop being enough but sooner or later it will. Also, to keep track of transactions and validation status, I need to refactor it anyway so I might as well move to a DB solution and get that done as well

**Comment by kulpreet** [comment]
Sqlite is kind of an obvious choice. But I thought leveldb will be an interesting one to use. Have you looked at it? Might be useful to evaluate it for our use case - see how our store can be implemented on top of it, etc.

**Comment by fazo96** [comment]
LevelDB would be great, the problem is that we need some kind of higher abstraction query API with the ability to store a very long list and only load into memory a piece of it when requested.

Unfortunately the levelDB api only has put/set and get so if we find a library that implements that kind of thing on top of a level API compatible DB then sure, otherwise we have to build that abstraction ourselves

**Comment by fazo96** [comment]
In JS, there is a module called LevelUP which takes interchangable level-compatible datastores. In the browser the most popular seems to be Level.js which implements the level api on top of IndexedDB. In node, the most popular is leveldown which is the native bindings for the actual reference implementation of leveldb.

Some databases and ORMs implemented on top of LevelUP: https://github.com/Level/levelup/wiki/Modules

The IPFS guys are using leveldown in node.js and level.js in the browser. The trick is the `browser` field in the `package.json` which is used to map `leveldown` to `level.js` so that webpack loads `level.js` while node.js loads `leveldown`.

This looks like the best solution to me

**Comment by fazo96** [comment]
We can use https://nanosql.io/ as a thin layer over IndexedDB/LevelDB so that the browser and nodejs can use the same code for the DB Index.

Problem is that I/O on this is async and we have to wait for OrbitDB to release the next version to be able to use it, so the not-all-in-memory index is kinda blocked until then.

**Comment by fazo96** [comment]
Update on this: OrbitDB now has async index updating. This is good because it unblocks using any database solution we want.

https://nanosql.io/ still looks like the best bet to me.
