### ISSUE TITLE
Make sure DID is published when publishing a review record that has been signed

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-ipfs-support#97]
If the DID was not published for some reason (like changing networks) the review record will never be valid

**Comment by kulpreet** [comment]
Well, what the solve here? Are we talking about forcing customers to have a chlu did before they can write a review?

**Comment by fazo96** [comment]
right now a DID is used to sign reviews as issuer by the customer if they are unverified (they come from the crawlers)

If they are verified, the customer signs as both issuer and customer. If the DID used has been imported by logging in, in some cases it does not get published. To make sure that it's published, we just need to check before signing and publish it if it's not. Otherwise the signature can't be checked and the review record won't go through.

**Comment by fazo96** [comment]
Long term we have to fix the DID thing so that it's not required

**Comment by fazo96** [comment]
Commits https://github.com/ChluNetwork/chlu-ipfs-support/pull/93/commits/b384fb49bf05fe47bdd4d3fb056ef5f646513c66 and https://github.com/ChluNetwork/chlu-ipfs-support/pull/93/commits/1537a14ebdd51d22be159f2a9093d2b169eee739 have a partial fix, want to talk it over with @kulpreet before making a final decision

**Comment by fazo96** [comment]
It's ok that the DID is required
